//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K.DB.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class queries_general {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal queries_general() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K.DB.Content.queries_general", typeof(queries_general).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COLUMN_NAME FROM {0}.INFORMATION_SCHEMA.COLUMNS WHERE   TABLE_NAME = {1}.
        /// </summary>
        internal static string INF_COLUMNS_2_SCHEMA_TABLE {
            get {
                return ResourceManager.GetString("INF_COLUMNS_2_SCHEMA,TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	 C.TABLE_CATALOG	as &apos;DBase&apos;
        ///		,C.TABLE_NAME		as &apos;Table&apos;
        ///		,C.COLUMN_NAME		as &apos;Name&apos;
        ///		,CASE WHEN U.COLUMN_NAME IS NULL THEN 0 ELSE 1 END
        ///							as &apos;PK&apos;
        ///		,C.CHARACTER_MAXIMUM_LENGTH
        ///							as &apos;Size&apos;
        ///		,CASE C.IS_NULLABLE WHEN &apos;YES&apos; THEN 1 ELSE 0 END
        ///							as &apos;Request&apos;
        ///		,DATA_TYPE			as &apos;Type&apos;
        ///FROM	 Teamsoft.INFORMATION_SCHEMA.COLUMNS C
        ///LEFT JOIN Teamsoft.INFORMATION_SCHEMA.KEY_COLUMN_USAGE U
        ///	ON	 C.TABLE_CATALOG = U.TABLE_CATALOG
        ///	AND	 C.TABLE_NAME = U.TABLE_NAME
        ///	AND	 C.COLUMN_NAME =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LOCAL_COLUMNS_4_DBASE_TABLE {
            get {
                return ResourceManager.GetString("LOCAL_COLUMNS_4_DBASE,TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 Description, TypeID FROM Teamsoft..ResultSet WHERE code LIKE &apos;{0}&apos;.
        /// </summary>
        internal static string LOCAL_RESULTSETINFO_1_CODE {
            get {
                return ResourceManager.GetString("LOCAL_RESULTSETINFO_1_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &quot;IntrnalKey&quot;, &quot;QName&quot; FROM OUQR WHERE &quot;QName&quot; LIKE {0} OR &quot;QString&quot; LIKE {1} ORDER BY &quot;QName&quot; ASC.
        /// </summary>
        internal static string OUQR_01LISTOFQUERIES_2_QNAME_QSTRING {
            get {
                return ResourceManager.GetString("OUQR_01LISTOFQUERIES_2_QNAME,QSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [{0}]..[@TS_PARAM0] (
        ///	 Code
        ///	,Name
        ///	,U_Project
        ///	,DocEntry	
        ///	,[Object]
        ///	,UserSign
        ///	,CreateDate
        ///	,CreateTime
        ///	,UpdateDate
        ///	,UpdateTime)
        ///VALUES (
        ///	 {1}
        ///	,&apos;{2}&apos;
        ///	,&apos;{3}&apos;
        ///	,(SELECT ISNULL(MAX(DocEntry),0) + 1 FROM [{0}]..[@TS_PARAM0])
        ///	,&apos;PARAM&apos;
        ///	,1
        ///	,cast(getdate() as date)
        ///	,1300
        ///	,cast(getdate() as date)
        ///	,1300).
        /// </summary>
        internal static string PARAM_ADDPARAM0_4_DBase_Code_Name_Project {
            get {
                return ResourceManager.GetString("PARAM_ADDPARAM0_4_DBase,Code,Name,Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	 U_VALUE
        ///FROM	 [{0}]..[@TS_PARAM1]
        ///WHERE	 Code = &apos;{1}&apos;
        ///	AND	 U_Name = &apos;{2}&apos;
        ///{6}	AND	 U_VAR1 = &apos;{3}&apos;
        ///{7}	AND	 U_VAR2 = &apos;{4}&apos;
        ///{8}	AND	 U_VAR3 = &apos;{5}&apos;
        ///	AND	 U_BPLID IS NULL
        ///	AND	 ( U_DUEDATE &gt;= CAST(GETDATE() as date)
        ///		OR U_DUEDATE IS NULL)
        ///ORDER BY U_ORDER asc.
        /// </summary>
        internal static string PARAM_GETVALUE_6_DBase_Name_Var123_BplId {
            get {
                return ResourceManager.GetString("PARAM_GETVALUE_6_DBase,Name,Var123,BplId", resourceCulture);
            }
        }
    }
}
